spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url:  jdbc:h2:file:./testdb;
    username: sa
    data:
   
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
     
  messages:
    basename: messages
    encoding: ISO-8859-1
  
  banner:
    location: classpath:/banner.txt
    
logging:
  file:
    name: pracCriteria
  level:
    root: ERROR
    org.hibernate.SQL: TRACE
    org.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8082